### ISSUE TITLE
New jsConnect protocol

### ISSUE THREAD

**Issue by tburry** [vanilla/addons#784]
Currently, jsConnect uses JSONP to authenticate with servers. This is problematic for the following reasons:

1. JSONP has known security issues, mainly that you can't control who makes the JSONP requests.
2. Browsers are starting to block third party cookies by default. This means that the JSONP protocol no longer works for authentication.

## Proposed Solution

I am proposing that we switch to a redirect workflow, similar to a two-legged OAuth flow, using JWT as the delivery. Here is what it might look like:

```
Vanilla    // Redirect to customer with request token, nonce
   |
   |
   v
 Client    // Validate request & redirect back to Vanilla with authorization token
   |
   |
   V
Vanilla    // Validate authorization token, nonce & sign SSO the user
```

One thing to note is that with jsConnect, the client is the authorization server which is the opposite of normal flows.

## Modifications Required

- [ ] Add a jsConnect setting to opt in to the new protocol.
- [ ] Modify the jsConnect redirect code to redirect with the new jsConnect token.
- [ ] Modify the client library to use the new redirect token.
- [ ] Modify `/entry/jsconnect` to POST the new token
- [ ] Validate the connect data event to validate the new token.
- [ ] Remove the detected signed in user code.

### Add a jsConnect setting to opt in to the new protocol

This is a matter of adding a radio button or a different hash algorithm for the new protocol.

### Modify the jsConnect redirect code to redirect with the new jsConnect token

The redirect will construct the authorization token and redirect in the same way as before, but it will use a JWT token. We will need to look if this can live alongside the old query string parameters so that the upgrade path is easier. We need to remember:

- The request token.
- Send a protocol version.
- Allow expandability (should be okay with JWT).

### Modify the client library to use the new redirect token

The client library can verify the JWT with a similar secret as before. It will construct its own JWT for the response and rather than echo it out it will redirect with it in the fragment of the return URL.

### Modify `/entry/jsconnect` to POST the new token

This is the page that currently makes the JSONP request. Now we'll do the following:

1. Check for the JWT.
2. If it finds it then it needs to POST it to '/entry/connect/jsconnect'

### Validate the connect data event to validate the new token.

The validation code does the following.

1. Look for the POSTed JWT.
2. Validate it and set the user data.

### Remove the detected signed in user code.

There is some code to show the currently signed in user. This is no longer supported so it needs to be removed. Instead, the sign in button is displayed.
